### ISSUE TITLE
Assert no longer has an .init() method

### ISSUE THREAD

**Issue by axtens** [andrewroberts/Subs-Test-Sheet#2]
I've noticed that Assert has been in active development for some time and that the version referenced in this project has long since been superseded. Modern versions of Assert no longer have an .init() method. 

I'm using Assert elsewhere have opted for a more recent version. What changes do I need to make to Subs-Test-Sheet Code.js to make it conform to the more recent version?

**Comment by andrewroberts** [comment]
Hi, It's exciting to see that someone is actually using the Subs library - I'd love to hear what you are using it on! I'll update the test script for the latest Assert library. Watch this space ...

**Comment by andrewroberts** [comment]
This is fixed now (v1.1) - the tests are updated for the latest Assert and BBLog libs.
